#ifndef __MESSAGE_H__
#define __MESSAGE_H__

typedef enum {
  T3_INPUT_EMPTY,
  T3_INPUT_INVALID,
  T3_INPUT_TOO_LONG,
  T3_EMAIL_INVALID,

  T3_DATABASE_INSERT_SUCCESS,
  T3_DATABASE_CONNECT_FAILED,
  T3_DATABASE_INSERT_FAILED,
  T3_USERNAME_ALREADY_EXISTS,
  T3_ACCOUNT_WRONG,
  T3_QUERY_FAILED,
  T3_SIGNIN_SUCCESS,

  T3_SERVER_NOT_FOUND,
  T3_INIT_CONNECT_FAILED,
  T3_SEND_REQUEST_FAILED,
  T3_REQUEST_TOO_LONG,
  T3_SERVER_CREATE_SOCKET_FAILED,
  T3_SERVER_BIND_SOCKET_FAILED,
  T3_SERVER_LISTEN_CONNECTION_FAILED,
  T3_REQUEST_REJECTED,

} Message;

void t3_message(char *, Message);

#endif