/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;
import controller.Client;
import java.io.IOException;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import static javax.swing.WindowConstants.EXIT_ON_CLOSE;
import javax.swing.table.DefaultTableModel;
import model.User;

/**
 *
 * @author Admin
 */
public class FriendListFrm extends javax.swing.JFrame {
  private List<User> listFriend;
  private boolean isClicked;
  private Thread thread;
  DefaultTableModel defaultTableModel;
  /**
   * Creates new form FriendListFrm
   */
  public FriendListFrm() {
    initComponents();
    defaultTableModel = (DefaultTableModel) jTable1.getModel();
    this.setTitle("Caro Master");
    this.setIconImage(new ImageIcon("assets/image/caroicon.png").getImage());
    this.setResizable(false);
    this.setDefaultCloseOperation(EXIT_ON_CLOSE);
    this.setLocationRelativeTo(null);
    isClicked = false;
    startThread();
  }

  public void stopAllThread(){
    isClicked = true;
  }

  public void startThread(){
    thread = new Thread() {
      @Override
      public void run() {
        while (Client.friendListFrm.isDisplayable() && !isClicked) {
          try {
            System.out.println("Xem danh sách bạn bè đang chạy!");
            requestUpdate();
            
            // Request liên tục: nếu có ai online sẽ hiển thị ngay lập tức
            Thread.sleep(2000);
          } catch (InterruptedException ex) {
            ex.printStackTrace();
          }
        }
      }
    };
    thread.start();
  }
  
  public void requestUpdate(){
    try {
      Client.socketHandle.write(Client.socketHandle.requestify("FRIEND_LIST", 0, "player_id=" + Client.user.getID(), ""));
    } catch (IOException ex) {
      JOptionPane.showMessageDialog(rootPane, ex.getMessage());
    }
  }
  
  public void updateFriendList(List<User> friends){
    listFriend = friends;
    defaultTableModel.setRowCount(0);
    ImageIcon icon;
    for(User friend : listFriend){
      if(!friend.isIsOnline()){
        icon = new ImageIcon("assets/icon/offline.png");
      }
      else if(friend.isIsPlaying()){
        icon = new ImageIcon("assets/icon/swords-mini.png");
      }
      else {
        icon = new ImageIcon("assets/icon/swords-1-mini.png");
      }
      
      defaultTableModel.addRow(new Object[]{
        "" + friend.getID(),
        friend.getUsername(),
        new ImageIcon(friend.getAvatar()),
        icon
      });
    }
  }


  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    jButton1 = new javax.swing.JButton();
    jScrollPane3 = new javax.swing.JScrollPane();
    Object[][] rows = {
    };
    String[] columns = {"ID","Username","Avatar", ""};
    DefaultTableModel model = new DefaultTableModel(rows, columns){
      @Override
      public Class<?> getColumnClass(int column){
        switch(column){
          case 0: return String.class;
          case 1: return String.class;
          case 2: return ImageIcon.class;
          case 3: return ImageIcon.class;
          default: return Object.class;
        }
      }
    };
    jTable1 = new javax.swing.JTable();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    jPanel1.setBackground(new java.awt.Color(102, 102, 102));

    jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
    jLabel1.setForeground(new java.awt.Color(255, 255, 255));
    jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel1.setText("Danh sách bạn bè");

    jButton1.setText("X");
    jButton1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton1ActionPerformed(evt);
      }
    });

    jTable1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
    jTable1.setModel(model);
    jTable1.setRowHeight(60);
    jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        jTable1MouseClicked(evt);
      }
    });
    jScrollPane3.setViewportView(jTable1);
    if (jTable1.getColumnModel().getColumnCount() > 0) {
      jTable1.getColumnModel().getColumn(0).setMinWidth(60);
      jTable1.getColumnModel().getColumn(0).setPreferredWidth(60);
      jTable1.getColumnModel().getColumn(0).setMaxWidth(60);
      jTable1.getColumnModel().getColumn(1).setMinWidth(240);
      jTable1.getColumnModel().getColumn(1).setPreferredWidth(240);
      jTable1.getColumnModel().getColumn(1).setMaxWidth(240);
      jTable1.getColumnModel().getColumn(2).setMinWidth(120);
      jTable1.getColumnModel().getColumn(2).setPreferredWidth(120);
      jTable1.getColumnModel().getColumn(2).setMaxWidth(120);
    }

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addComponent(jButton1)
        .addGap(0, 0, Short.MAX_VALUE))
      .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jScrollPane3)
        .addContainerGap())
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
        .addComponent(jButton1)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jLabel1)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap())
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      Client.closeView(Client.View.FRIENDLIST);
      Client.openView(Client.View.HOMEPAGE);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
      try {
        if(jTable1.getSelectedRow() == -1) return;
        User friend = listFriend.get(jTable1.getSelectedRow());
        if(!friend.isIsOnline()){
          throw new Exception("Người chơi không online");
        }
        if(friend.isIsPlaying()){
          throw new Exception("Người chơi đang trong trận đấu");
        }
        isClicked = true;
        int res = JOptionPane.showConfirmDialog(rootPane, "Bạn có muốn thách đấu người bạn này không", "Xác nhận thách đấu", JOptionPane.YES_NO_OPTION);
        if(res == JOptionPane.YES_OPTION){
          Client.closeAllViews();
          Client.openView(Client.View.GAMENOTICE, "Thách đấu", "Đang chờ phản hồi từ đối thủ");
          Client.socketHandle.write(Client.socketHandle.requestify("DUEL_REQUEST", 0, "player_id=" + Client.user.getID() + "&friend_id=" + friend.getID(), ""));
        }
        else{
          isClicked = false;
          startThread();
        }
      } catch (IOException ex) {
        JOptionPane.showMessageDialog(rootPane, ex.getMessage());
      } catch (Exception ex) {
        JOptionPane.showMessageDialog(rootPane, ex.getMessage());
      }
    }//GEN-LAST:event_jTable1MouseClicked


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jButton1;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JScrollPane jScrollPane3;
  private javax.swing.JTable jTable1;
  // End of variables declaration//GEN-END:variables
}
