#ifndef __ERROR_H__
#define __ERROR_H__

typedef enum {
    ERR_ACCOUNT_NON_ACTIVATED,
    ERR_ACCOUNT_BLOCKED,
    ERR_ACCOUNT_EXISTED,
    ERR_ACCOUNT_NOT_FOUND,
    ERR_ACTIVATION_CODE_INCORRECT,
    ERR_INPUT_EMPTY,
    ERR_INPUT_INVALID,
    ERR_INVALID_SERVER_ARGUMENT,
    ERR_INVALID_CLIENT_ARGUMENT,
    ERR_INVALID_DOMAIN_NAME,
    ERR_INVALID_PORT,
    ERR_INVALID_HOMEPAGE_ADDRESS,
    ERR_INVALID_IPv4,
    ERR_MEMORY_FULL,
    ERR_NON_LOG_IN,
    ERR_OPEN_FILE,
    ERR_OPTION,
    ERR_PASSWORD_INCORRECT,
    ERR_RESOLVE_IP,
    ERR_SERVER_ERROR,
    ERR_USERNAME_INCORRECT,
    ERR_SEND_REQUEST_FAILED,
    ERR_SEND_RESPONSE_FAILED,
    ERR_GET_REQUEST_FAILED,
    ERR_GET_RESPONSE_FAILED,
    ERR_REQUEST_TOO_LONG,
    ERR_UNKNOWN_RESOURCE,
    ERR_INITIALIZE_SOCKET_FAILED,
    ERR_SERVER_NOT_FOUND,
    ERR_REGISTER_ACCOUNT_FAILED,
} ErrorCode;

void err_error(ErrorCode);

#endif